const images = {
  apple: require('./apple.png'),
  avocado: require('./avocado.png'),
  bacon: require('./bacon.png'),
  banana: require('./banana.png'),
  basil: require('./basil.png'),
  cheese: require('./cheese.png'),
  cherrytomatoes: require('./cherrytomatoes.png'),
  chorizo: require('./chorizo.png'),
  cucumber: require('./cucumber.png'),
  egg: require('./egg.png'),
  friedfillet: require('./friedfillet.png'),
  greenbellpepper: require('./greenbellpepper.png'),
  ham: require('./ham.png'),
  hamburger: require('./hamburger.png'),
  herbedsausage: require('./herbedsausage.png'),
  jalapeno: require('./jalapeno.png'),
  kiwi: require('./kiwi.png'),
  klawfstick: require('./klawfstick.png'),
  lettuce: require('./lettuce.png'),
  noodles: require('./noodles.png'),
  onion: require('./onion.png'),
  pickle: require('./pickle.png'),
  pineapple: require('./pineapple.png'),
  potatosalad: require('./potatosalad.png'),
  potatotorilla: require('./potatotorilla.png'),
  prosciutto: require('./prosciutto.png'),
  redbellpepper: require('./redbellpepper.png'),
  redonion: require('./redonion.png'),
  rice: require('./rice.png'),
  smokedfillet: require('./smokedfillet.png'),
  strawberry: require('./strawberry.png'),
  tofu: require('./tofu.png'),
  tomato: require('./tomato.png'),
  watercress: require('./watercress.png'),
  yellowbellpepper: require('./yellowbellpepper.png'),
}

export default images