const images = {
  bitterherbamystica: require('./bitterherbamystica.png'),
  butter: require('./butter.png'),
  chilisauce: require('./chilisauce.png'),
  creamcheese: require('./creamcheese.png'),
  currypowder: require('./currypowder.png'),
  horseradish: require('./horseradish.png'),
  jam: require('./jam.png'),
  ketchup: require('./ketchup.png'),
  marmalade: require('./marmalade.png'),
  mayonnaise: require('./mayonnaise.png'),
  mustard: require('./mustard.png'),
  oliveoil: require('./oliveoil.png'),
  peanutbutter: require('./peanutbutter.png'),
  pepper: require('./pepper.png'),
  salt: require('./salt.png'),
  saltyherbamystica: require('./saltyherbamystica.png'),
  sourherbamystica: require('./sourherbamystica.png'),
  spicyherbamystica: require('./spicyherbamystica.png'),
  sweetherbamystica: require('./sweetherbamystica.png'),
  vinegar: require('./vinegar.png'),
  wasabi: require('./wasabi.png'),
  whippedcream: require('./whippedcream.png'),
  yogurt: require('./yogurt.png'),
}

export default images